### ISSUE TITLE
Add support for setting the hook to use

### ISSUE THREAD

**Issue by dasa** [paulmelnikow/rollup-plugin-cpy#58]
Similar to: https://github.com/vladshcherbin/rollup-plugin-copy#hook

The current `writeBundle` hook is good for when this plugin is used as an output plugin, but it causes the plugin to copy the files once per output when used in the options's plugins.

`buildEnd` is maybe a better default to avoid this issue.

**Comment by paulmelnikow** [comment]
I'm happy to accept a pull request for this!

**Comment by dasa** [comment]
I'm not sure where this new `hook` option should go since currently you support passing in an array of options and the `hook` option should apply to all and not only one of them. The plugin could accept a second parameter but I haven't seen any Rollup plugins doing that.

**Comment by paulmelnikow** [comment]
Why not allow setting it separately for each item in the array?

**Comment by dasa** [comment]
It seems like it'd get a bit complicated to implement since each option would need to be grouped and handled with its corresponding hook.

**Comment by paulmelnikow** [comment]
Oops, I clicked close by mistake.

I'm not sure what's involved in setting a custom hook, though It doesn't seem like the implementation would be that bad, though if you see a different way that seems better, I'm open to it.

**Comment by dasa** [comment]
Thank you for discussing this with me. I've found an alternative so I'm closing this request.
